/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WithSidebarImport } from './routes/_with-sidebar'
import { Route as WithFooterImport } from './routes/_with-footer'
import { Route as AuthImport } from './routes/_auth'
import { Route as WithSidebarChatImport } from './routes/_with-sidebar/chat'
import { Route as WithFooterWithHeaderImport } from './routes/_with-footer/_with-header'
import { Route as WithFooterWithHeaderIndexImport } from './routes/_with-footer/_with-header/index'
import { Route as WithSidebarChatIdImport } from './routes/_with-sidebar/chat_/$id'
import { Route as WithFooterWithHeaderBibleImport } from './routes/_with-footer/_with-header/bible'
import { Route as WithFooterWithHeaderBibleBibleAbbreviationImport } from './routes/_with-footer/_with-header/bible_/$bibleAbbreviation'
import { Route as WithFooterWithHeaderBibleBibleAbbreviationBookCodeImport } from './routes/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode'
import { Route as WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberImport } from './routes/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber'
import { Route as WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberVerseNumberImport } from './routes/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber_/$verseNumber'

// Create/Update Routes

const WithSidebarRoute = WithSidebarImport.update({
  id: '/_with-sidebar',
  getParentRoute: () => rootRoute,
} as any)

const WithFooterRoute = WithFooterImport.update({
  id: '/_with-footer',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const WithSidebarChatRoute = WithSidebarChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => WithSidebarRoute,
} as any)

const WithFooterWithHeaderRoute = WithFooterWithHeaderImport.update({
  id: '/_with-header',
  getParentRoute: () => WithFooterRoute,
} as any)

const WithFooterWithHeaderIndexRoute = WithFooterWithHeaderIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WithFooterWithHeaderRoute,
} as any)

const WithSidebarChatIdRoute = WithSidebarChatIdImport.update({
  id: '/chat_/$id',
  path: '/chat/$id',
  getParentRoute: () => WithSidebarRoute,
} as any)

const WithFooterWithHeaderBibleRoute = WithFooterWithHeaderBibleImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => WithFooterWithHeaderRoute,
} as any)

const WithFooterWithHeaderBibleBibleAbbreviationRoute =
  WithFooterWithHeaderBibleBibleAbbreviationImport.update({
    id: '/bible_/$bibleAbbreviation',
    path: '/bible/$bibleAbbreviation',
    getParentRoute: () => WithFooterWithHeaderRoute,
  } as any)

const WithFooterWithHeaderBibleBibleAbbreviationBookCodeRoute =
  WithFooterWithHeaderBibleBibleAbbreviationBookCodeImport.update({
    id: '/bible_/$bibleAbbreviation_/$bookCode',
    path: '/bible/$bibleAbbreviation/$bookCode',
    getParentRoute: () => WithFooterWithHeaderRoute,
  } as any)

const WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberRoute =
  WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberImport.update({
    id: '/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber',
    path: '/bible/$bibleAbbreviation/$bookCode/$chapterNumber',
    getParentRoute: () => WithFooterWithHeaderRoute,
  } as any)

const WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberVerseNumberRoute =
  WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberVerseNumberImport.update(
    {
      id: '/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber_/$verseNumber',
      path: '/bible/$bibleAbbreviation/$bookCode/$chapterNumber/$verseNumber',
      getParentRoute: () => WithFooterWithHeaderRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_with-footer': {
      id: '/_with-footer'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithFooterImport
      parentRoute: typeof rootRoute
    }
    '/_with-sidebar': {
      id: '/_with-sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithSidebarImport
      parentRoute: typeof rootRoute
    }
    '/_with-footer/_with-header': {
      id: '/_with-footer/_with-header'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WithFooterWithHeaderImport
      parentRoute: typeof WithFooterImport
    }
    '/_with-sidebar/chat': {
      id: '/_with-sidebar/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof WithSidebarChatImport
      parentRoute: typeof WithSidebarImport
    }
    '/_with-footer/_with-header/bible': {
      id: '/_with-footer/_with-header/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof WithFooterWithHeaderBibleImport
      parentRoute: typeof WithFooterWithHeaderImport
    }
    '/_with-sidebar/chat_/$id': {
      id: '/_with-sidebar/chat_/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof WithSidebarChatIdImport
      parentRoute: typeof WithSidebarImport
    }
    '/_with-footer/_with-header/': {
      id: '/_with-footer/_with-header/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WithFooterWithHeaderIndexImport
      parentRoute: typeof WithFooterWithHeaderImport
    }
    '/_with-footer/_with-header/bible_/$bibleAbbreviation': {
      id: '/_with-footer/_with-header/bible_/$bibleAbbreviation'
      path: '/bible/$bibleAbbreviation'
      fullPath: '/bible/$bibleAbbreviation'
      preLoaderRoute: typeof WithFooterWithHeaderBibleBibleAbbreviationImport
      parentRoute: typeof WithFooterWithHeaderImport
    }
    '/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode': {
      id: '/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode'
      path: '/bible/$bibleAbbreviation/$bookCode'
      fullPath: '/bible/$bibleAbbreviation/$bookCode'
      preLoaderRoute: typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeImport
      parentRoute: typeof WithFooterWithHeaderImport
    }
    '/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber': {
      id: '/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber'
      path: '/bible/$bibleAbbreviation/$bookCode/$chapterNumber'
      fullPath: '/bible/$bibleAbbreviation/$bookCode/$chapterNumber'
      preLoaderRoute: typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberImport
      parentRoute: typeof WithFooterWithHeaderImport
    }
    '/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber_/$verseNumber': {
      id: '/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber_/$verseNumber'
      path: '/bible/$bibleAbbreviation/$bookCode/$chapterNumber/$verseNumber'
      fullPath: '/bible/$bibleAbbreviation/$bookCode/$chapterNumber/$verseNumber'
      preLoaderRoute: typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberVerseNumberImport
      parentRoute: typeof WithFooterWithHeaderImport
    }
  }
}

// Create and export the route tree

interface WithFooterWithHeaderRouteChildren {
  WithFooterWithHeaderBibleRoute: typeof WithFooterWithHeaderBibleRoute
  WithFooterWithHeaderIndexRoute: typeof WithFooterWithHeaderIndexRoute
  WithFooterWithHeaderBibleBibleAbbreviationRoute: typeof WithFooterWithHeaderBibleBibleAbbreviationRoute
  WithFooterWithHeaderBibleBibleAbbreviationBookCodeRoute: typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeRoute
  WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberRoute: typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberRoute
  WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberVerseNumberRoute: typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberVerseNumberRoute
}

const WithFooterWithHeaderRouteChildren: WithFooterWithHeaderRouteChildren = {
  WithFooterWithHeaderBibleRoute: WithFooterWithHeaderBibleRoute,
  WithFooterWithHeaderIndexRoute: WithFooterWithHeaderIndexRoute,
  WithFooterWithHeaderBibleBibleAbbreviationRoute:
    WithFooterWithHeaderBibleBibleAbbreviationRoute,
  WithFooterWithHeaderBibleBibleAbbreviationBookCodeRoute:
    WithFooterWithHeaderBibleBibleAbbreviationBookCodeRoute,
  WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberRoute:
    WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberRoute,
  WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberVerseNumberRoute:
    WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberVerseNumberRoute,
}

const WithFooterWithHeaderRouteWithChildren =
  WithFooterWithHeaderRoute._addFileChildren(WithFooterWithHeaderRouteChildren)

interface WithFooterRouteChildren {
  WithFooterWithHeaderRoute: typeof WithFooterWithHeaderRouteWithChildren
}

const WithFooterRouteChildren: WithFooterRouteChildren = {
  WithFooterWithHeaderRoute: WithFooterWithHeaderRouteWithChildren,
}

const WithFooterRouteWithChildren = WithFooterRoute._addFileChildren(
  WithFooterRouteChildren,
)

interface WithSidebarRouteChildren {
  WithSidebarChatRoute: typeof WithSidebarChatRoute
  WithSidebarChatIdRoute: typeof WithSidebarChatIdRoute
}

const WithSidebarRouteChildren: WithSidebarRouteChildren = {
  WithSidebarChatRoute: WithSidebarChatRoute,
  WithSidebarChatIdRoute: WithSidebarChatIdRoute,
}

const WithSidebarRouteWithChildren = WithSidebarRoute._addFileChildren(
  WithSidebarRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof WithFooterWithHeaderRouteWithChildren
  '/chat': typeof WithSidebarChatRoute
  '/bible': typeof WithFooterWithHeaderBibleRoute
  '/chat/$id': typeof WithSidebarChatIdRoute
  '/': typeof WithFooterWithHeaderIndexRoute
  '/bible/$bibleAbbreviation': typeof WithFooterWithHeaderBibleBibleAbbreviationRoute
  '/bible/$bibleAbbreviation/$bookCode': typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeRoute
  '/bible/$bibleAbbreviation/$bookCode/$chapterNumber': typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberRoute
  '/bible/$bibleAbbreviation/$bookCode/$chapterNumber/$verseNumber': typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberVerseNumberRoute
}

export interface FileRoutesByTo {
  '': typeof WithSidebarRouteWithChildren
  '/chat': typeof WithSidebarChatRoute
  '/bible': typeof WithFooterWithHeaderBibleRoute
  '/chat/$id': typeof WithSidebarChatIdRoute
  '/': typeof WithFooterWithHeaderIndexRoute
  '/bible/$bibleAbbreviation': typeof WithFooterWithHeaderBibleBibleAbbreviationRoute
  '/bible/$bibleAbbreviation/$bookCode': typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeRoute
  '/bible/$bibleAbbreviation/$bookCode/$chapterNumber': typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberRoute
  '/bible/$bibleAbbreviation/$bookCode/$chapterNumber/$verseNumber': typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberVerseNumberRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRoute
  '/_with-footer': typeof WithFooterRouteWithChildren
  '/_with-sidebar': typeof WithSidebarRouteWithChildren
  '/_with-footer/_with-header': typeof WithFooterWithHeaderRouteWithChildren
  '/_with-sidebar/chat': typeof WithSidebarChatRoute
  '/_with-footer/_with-header/bible': typeof WithFooterWithHeaderBibleRoute
  '/_with-sidebar/chat_/$id': typeof WithSidebarChatIdRoute
  '/_with-footer/_with-header/': typeof WithFooterWithHeaderIndexRoute
  '/_with-footer/_with-header/bible_/$bibleAbbreviation': typeof WithFooterWithHeaderBibleBibleAbbreviationRoute
  '/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode': typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeRoute
  '/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber': typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberRoute
  '/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber_/$verseNumber': typeof WithFooterWithHeaderBibleBibleAbbreviationBookCodeChapterNumberVerseNumberRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/chat'
    | '/bible'
    | '/chat/$id'
    | '/'
    | '/bible/$bibleAbbreviation'
    | '/bible/$bibleAbbreviation/$bookCode'
    | '/bible/$bibleAbbreviation/$bookCode/$chapterNumber'
    | '/bible/$bibleAbbreviation/$bookCode/$chapterNumber/$verseNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/chat'
    | '/bible'
    | '/chat/$id'
    | '/'
    | '/bible/$bibleAbbreviation'
    | '/bible/$bibleAbbreviation/$bookCode'
    | '/bible/$bibleAbbreviation/$bookCode/$chapterNumber'
    | '/bible/$bibleAbbreviation/$bookCode/$chapterNumber/$verseNumber'
  id:
    | '__root__'
    | '/_auth'
    | '/_with-footer'
    | '/_with-sidebar'
    | '/_with-footer/_with-header'
    | '/_with-sidebar/chat'
    | '/_with-footer/_with-header/bible'
    | '/_with-sidebar/chat_/$id'
    | '/_with-footer/_with-header/'
    | '/_with-footer/_with-header/bible_/$bibleAbbreviation'
    | '/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode'
    | '/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber'
    | '/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber_/$verseNumber'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  WithFooterRoute: typeof WithFooterRouteWithChildren
  WithSidebarRoute: typeof WithSidebarRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  WithFooterRoute: WithFooterRouteWithChildren,
  WithSidebarRoute: WithSidebarRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_with-footer",
        "/_with-sidebar"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx"
    },
    "/_with-footer": {
      "filePath": "_with-footer.tsx",
      "children": [
        "/_with-footer/_with-header"
      ]
    },
    "/_with-sidebar": {
      "filePath": "_with-sidebar.tsx",
      "children": [
        "/_with-sidebar/chat",
        "/_with-sidebar/chat_/$id"
      ]
    },
    "/_with-footer/_with-header": {
      "filePath": "_with-footer/_with-header.tsx",
      "parent": "/_with-footer",
      "children": [
        "/_with-footer/_with-header/bible",
        "/_with-footer/_with-header/",
        "/_with-footer/_with-header/bible_/$bibleAbbreviation",
        "/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode",
        "/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber",
        "/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber_/$verseNumber"
      ]
    },
    "/_with-sidebar/chat": {
      "filePath": "_with-sidebar/chat.tsx",
      "parent": "/_with-sidebar"
    },
    "/_with-footer/_with-header/bible": {
      "filePath": "_with-footer/_with-header/bible.tsx",
      "parent": "/_with-footer/_with-header"
    },
    "/_with-sidebar/chat_/$id": {
      "filePath": "_with-sidebar/chat_/$id.tsx",
      "parent": "/_with-sidebar"
    },
    "/_with-footer/_with-header/": {
      "filePath": "_with-footer/_with-header/index.tsx",
      "parent": "/_with-footer/_with-header"
    },
    "/_with-footer/_with-header/bible_/$bibleAbbreviation": {
      "filePath": "_with-footer/_with-header/bible_/$bibleAbbreviation.tsx",
      "parent": "/_with-footer/_with-header"
    },
    "/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode": {
      "filePath": "_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode.tsx",
      "parent": "/_with-footer/_with-header"
    },
    "/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber": {
      "filePath": "_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber.tsx",
      "parent": "/_with-footer/_with-header"
    },
    "/_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber_/$verseNumber": {
      "filePath": "_with-footer/_with-header/bible_/$bibleAbbreviation_/$bookCode_/$chapterNumber_/$verseNumber.tsx",
      "parent": "/_with-footer/_with-header"
    }
  }
}
ROUTE_MANIFEST_END */
