services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    profiles:
      - "default"
      - "backend-dev"
      - "frontend-dev"

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - ./volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    profiles:
      - "default"
      - "backend-dev"
      - "frontend-dev"

  milvus:
    image: milvusdb/milvus:v2.2.9
    command: ["milvus", "run", "standalone"]
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    profiles:
      - "default"
      - "backend-dev"
      - "frontend-dev"

  attu:
    image: zilliz/attu:v2.2.3
    environment:
      MILVUS_URL: milvus:19530
    ports:
      - "8090:3000"
    depends_on:
      - "milvus"
    profiles:
      - "backend-dev"

  postgres:
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=septuagint
    profiles:
      - "default"
      - "backend-dev"
      - "frontend-dev"

  redis:
    image: redis:7.0.11
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis:/data
    profiles:
      - "default"
      - "backend-dev"
      - "frontend-dev"

  unstructured-api:
    image: quay.io/unstructured-io/unstructured-api:0.0.23
    ports:
      - 8000:8000
    command: --host 0.0.0.0 --port 8000
    profiles:
      - "default"
      - "backend-dev"
      - "frontend-dev"

  local-ai:
    image: quay.io/go-skynet/local-ai:latest
    ports:
      - 8081:8080
    environment:
      - MODELS_PATH=/models
    volumes:
      - ./models:/models:cached
    profiles:
      - "local-ai"

  backend:
    image: septuagint/backend:0.0.1
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
    environment:
      - MILVUS_URL=http://milvus:19530
      - MILVUS_COLLECTION_NAME=septuagint
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=septuagint
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - milvus
      - postgres
      - redis
      - unstructured-api
    profiles:
      - "default"
      - "frontend-dev"
