name: 'CI Setup'
description: 'CI setup for The AI Study Bible'

runs:
  using: 'composite'
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Cache TurboRepo
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-${{ runner.arch }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-turbo-

    - name: Cache Docker Buildx from SST
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-${{ runner.arch }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-buildx-

    - name: Install dependencies
      shell: bash
      run: |
        bun install --frozen-lockfile

    - name: Install SST Providers
      shell: bash
      run: |
        bun sst install
    
    - name: Authenticate with GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'
      
    - name: Set up gcloud sdk
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Setup docker auth for GCP
      shell: bash
      run: |
          gcloud auth configure-docker -q
