export const DEVO_BIBLE_READING_CHAIN_PROMPT_TEMPLATE = `You need to find a Bible reading within the following documents and based on the following topic. Your output should match the formatting instructions exactly. You are also given a list of off-limits Bible readings, which you should not use.

The off-limits Bible readings are within <off_limits_bible_readings></off_limits_bible_readings> XML tags. Each individual Bible reading is encapsulated within <bible_reading></bible_reading> XML tags. **IMPORTANT:** You are not allowed to use any of these Bible readings under any circumstances!!

The documents are within <documents></documents> XML tags. Each individual document is encapsulated within <document></document> XML tags. **IMPORTANT:** These documents are where you are to pull your Bible reading from, **not the previous Bible readings!!**

The topic is within <topic></topic> XML tags.

The formatting instructions are within <format_instructions></format_instructions> XML tags.

<off_limits_bible_readings>
{previousBibleReadings}
</off_limits_bible_readings>

<documents>
{documents}
</documents>

<topic>
{topic}
</topic>

<format_instructions>
{formatInstructions}
</format_instructions>

Put your output that follows the formatting instructions within <output></output> XML tags.`;

export const DEVO_GENERATOR_CHAIN_PROMPT_TEMPLATE = `You need to write a non-denominational Christian devotion based on the following topic and Bible reading. The devotion should mainly be about the topic with references to the Bible reading where necessary. Use the documents provided to you to add more detail to your output. Your output should match the formatting instructions exactly.

The topic is within <topic></topic> XML tags.

The Bible reading is within <bible_reading></bible_reading> XML tags.

The documents are within <documents></documents> XML tags. Each individual document is encapsulated within <document></document> XML tags.

The formatting instructions are within <format_instructions></format_instructions> XML tags.

<topic>
{topic}
</topic>

<bible_reading>
{bibleReading}
</bible_reading>

<format_instructions>
{formatInstructions}
</format_instructions>

<documents>
{documents}
</documents>

Put your output that follows the formatting instructions within <output></output> XML tags.`;

export const DEVO_IMAGE_PROMPT_CHAIN_PROMPT_TEMPLATE = `You goal is to generate short, concise, yet descriptive phrases that can help when generating **ONE** stable diffusion model image. This image will be used to aid in visualizing the devotion that is also provided to you. Use **ONLY** the devotion provided to make these phrases as descriptive as possible. The more descriptive the phrases are, the better the image will be. Everything from your phrases should be able to be captured within **ONE** image and should not conflict with one another. **DO NOT** include dialogue or sounds in your output. These phrases should not be proper sentences. Your output must match the formatting instructions exactly.
      
An example is provided within <example></example> XML tags.

The devotion is within <devotion></devotion> XML tags.

The formatting instructions are within <format_instructions></format_instructions> XML tags.

<example>
\`\`\`json ["a man with long hair, a beard, and a crown of thorns on his head is nailed to a cross","women weeping and mourning at the foot of the cross","soldiers standing guard at the foot of the cross","a sign on the cross in a foreign language"]\`\`\`
</example>

<devotion>
Bible Reading:\n{bibleReading}\n\n
Summary:\n{summary}\n\n
Reflection:\n{reflection}\n\n
Prayer:\n{prayer}\n\n
</devotion>

<format_instructions>
{formatInstructions}
</format_instructions>

Put your output that follows the formatting instructions within <output></output> XML tags.`;

export const DEVO_IMAGE_CAPTION_CHAIN_PROMPT_TEMPLATE = `Generate a caption for the image that would be generated by the following prompt and devotion. Your caption should not be more than 100 words in length.

The prompt is within <prompt></prompt> XML tags.

The devotion is within <devotion></devotion> XML tags.

<prompt>
{imagePrompt}
</prompt>

<devotion>
Bible Reading:\n{bibleReading}\n\n
Summary:\n{summary}\n\n
Reflection:\n{reflection}\n\n
Prayer:\n{prayer}\n
</devotion>

Put the caption you come up with within <output></output> XML tags.`;
