name: 'CI cleanup'
description: 'CI cleanup for The AI Study Bible'

runs:
  using: 'composite'
  steps:
    - name: Replace old buildx cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
