name: Mobile Build
concurrency: mobile
on:
  push:
    branches: [master]
    # only run if there are changes to the mobile directory
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
    paths:
      - mobile/**
  workflow_dispatch:
    inputs:
      build_android:
        type: boolean
        description: "Build Android"
        default: true
      build_ios:
        type: boolean
        description: "Build iOS"
        default: true

# TODO: Figure out how to get these from a single source of truth
env:
  WEBSITE_URL: https://revelationsai.com
  API_URL: https://api.revelationsai.com
  CHAT_API_URL: https://v2pnd3an3d42xw3hq3stiwij240ssycn.lambda-url.us-east-1.on.aws/

jobs:
  build_android:
    if: inputs.build_android || true
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: "11"
      - id: setup_flutter
        name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - id: flutter_doctor
        name: Run Flutter Doctor
        run: flutter doctor -v
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: install_dependencies
        name: Install dependencies
        run: flutter pub get
        working-directory: mobile
      - id: generate_code
        name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
        working-directory: mobile
      - id: build_appbundle
        name: Build App Bundle for Android
        run: flutter build appbundle --release
        working-directory: mobile
      - name: Archive App Bundle
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: mobile/build/app/outputs/bundle/release/app-release.aab

  build_ios:
    if: inputs.build_ios || true
    name: IOS Build
    runs-on: macos-latest
    steps:
      - id: setup_flutter
        name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - id: flutter_doctor
        name: Run Flutter Doctor
        run: flutter doctor -v
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: install_dependencies
        name: Install dependencies
        run: flutter pub get
        working-directory: mobile
      - id: generate_code
        name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
        working-directory: mobile
      - id: build_ipa
        name: Build iOS IPA
        run: flutter build ipa --release --no-codesign
        working-directory: mobile
      - name: Archive IPA
        uses: actions/upload-artifact@v2
        with:
          name: ios
          path: mobile/build/ios/archive/Runner.xcarchive
