name: Remove PR Preview

on:
  pull_request:
    types: [closed]
    branches: [master]

concurrency: pr-${{ github.event.pull_request.number }}

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
  TURSO_ORG: ${{ vars.TURSO_ORG }}
  TURSO_API_KEY: ${{ secrets.TURSO_API_KEY }}
  UPSTASH_EMAIL: ${{ vars.UPSTASH_EMAIL }}
  UPSTASH_API_KEY: ${{ secrets.UPSTASH_API_KEY }}
  STRIPE_API_KEY: ${{ secrets.DEV_STRIPE_SECRET_KEY }}
  SENTRY_ORG: ${{ vars.SENTRY_ORG }}
  SENTRY_TEAM: ${{ vars.SENTRY_TEAM }}
  SENTRY_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  remove:
    name: Remove
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: CI setup
        uses: ./.github/actions/ci-setup

      - name: Set SST Stage
        run: |
          echo "pr-${{ github.event.pull_request.number }}" > .sst/stage

      - name: Remove
        run: |
          bun run remove
