name: Deploy to production

on:
  push:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - '.vscode'
      - '.cursorrules'
      - '.github'
  workflow_dispatch:

concurrency: production

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
  TURSO_ORG: ${{ vars.TURSO_ORG }}
  TURSO_API_KEY: ${{ secrets.TURSO_API_KEY }}
  UPSTASH_EMAIL: ${{ vars.UPSTASH_EMAIL }}
  UPSTASH_API_KEY: ${{ secrets.UPSTASH_API_KEY }}
  STRIPE_API_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  SENTRY_ORG: ${{ vars.SENTRY_ORG }}
  SENTRY_TEAM: ${{ vars.SENTRY_TEAM }}
  SENTRY_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: CI setup
        uses: ./.github/actions/ci-setup

      - name: Type check
        run: |
          bun run type-check

      - name: Lint
        run: |
          bun run lint

      - name: Set SST Stage
        run: |
          echo "production" > .sst/stage

      - name: Deploy
        run: |
          bun run deploy

      - name: Run DB migrations
        run: |
          bun run db:migrate

      - name: Seed DB
        run: |
          bun run db:seed
