name: Production Deployment
concurrency: prod
on:
  push:
    branches: [master]
    paths-ignore:
      - ".github/**"
      - ".devcontainer/**"
      - ".vscode/**"
      - ".gitignore"
      - "README.md"
      - "mobile/**"
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}

  VECTOR_DB_DOCS_TABLE: ${{ vars.VECTOR_DB_DOCS_TABLE }}
  VECTOR_DB_DOCS_DIMENSIONS: ${{ vars.VECTOR_DB_DOCS_DIMENSIONS }}

  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  LLM_PROMPT_MODEL_NAME: ${{ vars.LLM_PROMPT_MODEL_NAME }}
  LLM_CHAT_MODEL_NAME: ${{ vars.LLM_CHAT_MODEL_NAME }}
  LLM_COMPLETIONS_MODEL_NAME: ${{ vars.LLM_COMPLETIONS_MODEL_NAME }}
  LLM_EMBEDDINGS_MODEL_NAME: ${{ vars.LLM_EMBEDDINGS_MODEL_NAME }}

  REPLICATE_API_KEY: ${{ secrets.REPLICATE_API_KEY }}
  REPLICATE_IMAGE_MODEL: ${{ vars.REPLICATE_IMAGE_MODEL }}

  UNSTRUCTURED_API_KEY: ${{ secrets.UNSTRUCTURED_API_KEY }}

  ENCODED_APPLE_AUTH_KEY: ${{ secrets.ENCODED_APPLE_AUTH_KEY }}
  APPLE_CLIENT_ID: ${{ vars.APPLE_CLIENT_ID }}
  APPLE_KEY_ID: ${{ vars.APPLE_KEY_ID }}
  APPLE_TEAM_ID: ${{ vars.APPLE_TEAM_ID }}

  GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}

  FACEBOOK_CLIENT_ID: ${{ vars.FACEBOOK_CLIENT_ID }}
  FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}

  EMAIL_FROM: ${{ vars.EMAIL_FROM }}
  EMAIL_REPLY_TO: ${{ vars.EMAIL_REPLY_TO }}
  EMAIL_SERVER_HOST: ${{ vars.EMAIL_SERVER_HOST }}
  EMAIL_SERVER_PORT: ${{ vars.EMAIL_SERVER_PORT }}
  EMAIL_SERVER_USERNAME: ${{ vars.EMAIL_SERVER_USERNAME }}
  EMAIL_SERVER_PASSWORD: ${{ secrets.EMAIL_SERVER_PASSWORD }}

  ADMIN_EMAIL: ${{ vars.ADMIN_EMAIL }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

  STRIPE_PUBLIC_KEY: ${{ vars.STRIPE_PUBLIC_KEY }}
  STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}

  ENCODED_FIREBASE_JSON: ${{ secrets.ENCODED_FIREBASE_JSON }}

jobs:
  deploy:
    name: Deploy Prod
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup_node
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - id: install_node_deps
        name: Install Node.js dependencies
        run: npm ci
      - id: setup_firebase_creds
        name: Setup Firebase Credentials
        run: |
          echo $ENCODED_FIREBASE_JSON | base64 --decode > firebase-service-account.json
      - id: setup_apple_auth_key
        name: Setup Apple Auth Key
        run: |
          echo $ENCODED_APPLE_AUTH_KEY | base64 --decode > apple-auth-key.p8
      - id: sst_deploy
        name: Deploy to AWS
        run: npx sst deploy --stage prod
