name: Remove a stage's resources

on:
  workflow_dispatch:
    inputs:
      stage:
        description: SST Stage
        required: true

concurrency: ${{ github.event.inputs.stage }}

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  FLY_ORG: ${{ vars.FLY_ORG }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TURSO_ORG: ${{ vars.TURSO_ORG }}
  TURSO_API_TOKEN: ${{ secrets.TURSO_API_KEY }}
  UPSTASH_EMAIL: ${{ vars.UPSTASH_EMAIL }}
  UPSTASH_API_KEY: ${{ secrets.UPSTASH_API_KEY }}
  STRIPE_API_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  SENTRY_ORG: ${{ vars.SENTRY_ORG }}
  SENTRY_TEAM: ${{ vars.SENTRY_TEAM }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  remove:
    name: Remove
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Setup GCP Credentials
        run: |
          echo ${{ secrets.GCP_KEY }} > gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp-key.json" >> $GITHUB_ENV

      - name: Set SST Stage
        run: |
          echo "${{ github.event.inputs.stage }}" > .sst/stage

      - name: Remove
        run: |
          bun run remove

      - name: CI Cleanup
        uses: ./.github/actions/ci-cleanup