name: Remove a stage's resources

on:
  workflow_dispatch:
    inputs:
      stage:
        description: SST Stage
        required: true

concurrency: ${{ github.event.inputs.stage }}

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
  TURSO_ORG: ${{ vars.TURSO_ORG }}
  TURSO_API_KEY: ${{ secrets.TURSO_API_KEY }}
  UPSTASH_EMAIL: ${{ vars.UPSTASH_EMAIL }}
  UPSTASH_API_KEY: ${{ secrets.UPSTASH_API_KEY }}
  STRIPE_API_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

jobs:
  remove:
    name: Remove
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: CI setup
        uses: ./.github/actions/ci-setup

      - name: Set SST Stage
        run: |
          echo "${{ github.event.inputs.stage }}" > .sst/stage

      - name: Remove
        run: |
          bun run remove
